name: Update Changelog
on:
  push:
    branches: [master]
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: tafy2392/database-entity-operator
          ref: ruru
          token: ${{ secrets.PAT }}
      - name: Update Changelog
        run: |
          echo "tanya1" >> CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: Update Changelog
          body: Update changelog to reflect release changes
          branch: update-changelog
          token: ${{ secrets.PAT }}
